### PR TITLE
Fix TLSV1_ALERT_PROTOCOL_VERSION errors due to out-of-date ssl support

### PR DESCRIPTION
**Pull request by joerick**

### CODE REVIEW

**Comment by PencilDH** [comment]
@joerick How can I get hotfix?

**Comment by joerick** [comment]
Which platform are you on?

**Comment by PencilDH** [comment]
macOS 10.12

**Comment by joerick** [comment]
https://s3.amazonaws.com/tingbot-builds/tingbot/tide-electron/164/164.3/dist/mac/Tide-0.5.5-mac.zip

**Comment by PencilDH** [comment]
Thank you, its still reporting old ssl version...

`OpenSSL 0.9.8zh 14 Jan 2016  `

**Comment by joerick** [comment]
Oh, sorry. Requests HTTPS requests are working - that's what I've been testing. They must be using a different ssl implementation, perhaps using the `cryptography` package. What's your use-case for openssl?

**Comment by PencilDH** [comment]
Hi Joe, Thank you for your help, fully up and running both in the simulator (5.7.0) and on the tingbot (after instaling pandas)!

Awsome !

**Comment by joerick** [comment]
Sweet, glad it's working :)

**Pull request merged**
