### PR TITLE
Pop open console when running apps, show debug output

### PR DESCRIPTION
**Pull request by joerick**
The console is also interactive - this will improve the user experience for plain Python apps as well as help when SSH login credentials are needed (among other things I'm sure)

### CODE REVIEW

**Comment by Rob4001** [comment]
Due to the native nature of pty.js there has been some incompatibility with some OSs.
Currently looking into if ptyw.js fixes these issues

**Comment by Rob4001** [comment]
pty.js doesn't work on linux or windows, ptyw.js does if you use electron-rebuild which ensures that native modules are recompiled with the correct node headers for he version of electron we are building for

**Comment by joerick** [comment]
Thanks for looking into that, Rob. I'll try and get it hooked up with ptyw and electron-rebuild

**Comment by joerick** [comment]
ptyw.js has a bug on Mac where it doesn't know the result code 🙄 ... but it does work. Probably best to start there and see if I can fix the return code issue.

**Comment by joerick** [comment]
Submitted [a PR](https://github.com/iiegor/ptyw.js/pull/20) to ptyw.js, we'll see if it gets merged soon. If not, we can use my fork.

**Comment by joerick** [comment]
Argh, I've been trying to set up a Windows 7 machine for development, but so far got nowhere (stuck with a node-gyp error). Have you got a working install @Rob4001 or @StefanJanssen95 ? If you got a chance, would you be able to test this branch to see if it's working now?

**Pull request merged**
